services:
  PrestaShop\PsAccountsInstaller\Installer\Installer:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Installer'
    arguments:
      - '3'

  PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts'
    arguments:
      - '@PrestaShop\PsAccountsInstaller\Installer\Installer'