services:
  PrestaShop\PsAccountsInstaller\Installer\Installer:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Installer'
    arguments:
      - !php/const PrestaShop\Module\PrestashopFacebook\Config\Config::COMPLIANT_PS_ACCOUNTS_VERSION

  PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts'
    arguments:
      - '@PrestaShop\PsAccountsInstaller\Installer\Installer'