enum ActionsTypes {
  WARMUP_STORE = 'WARMUP_STORE',

  REQUEST_SYNCHRONIZATION_STATS = 'REQUEST_SYNCHRONIZATION_STATS',
  REQUEST_TOGGLE_SYNCHRONIZATION = 'REQUEST_TOGGLE_SYNCHRONIZATION',
  REQUEST_PRODUCT_SCAN = 'REQUEST_PRODUCT_SCAN',
  REQUEST_NEXT_SYNC_AS_FULL = 'REQUEST_NEXT_SYNC_AS_FULL',

  REQUEST_CATEGORY_MAPPING_STATS = 'REQUEST_CATEGORY_MAPPING_STATS',
  REQUEST_CATEGORY_MAPPING_LIST = 'REQUEST_CATEGORY_MAPPING_LIST',
}

export {ActionsTypes as default};
