enum GettersTypes {
  // Sync subscription
  GET_CATALOG_PAGE_ENABLED = 'GET_CATALOG_PAGE_ENABLED',
  GET_SYNCHRONIZATION_ACTIVE = 'GET_SYNCHRONIZATION_ACTIVE',

  // Product feed
  GET_SYNCHRONIZATION_SUMMARY = 'GET_SYNCHRONIZATION_SUMMARY',

  // Category matching
  GET_CATEGORY_MATCHING_SUMMARY = 'GET_CATEGORY_MATCHING_SUMMARY',
}

export {GettersTypes as default};
