enum MutationsTypes {
  SET_CATALOG_PAGE_ENABLED = 'SET_CATALOG_PAGE_ENABLED',
  SET_SYNCHRONIZATION_ACTIVE = 'SET_SYNCHRONIZATION_ACTIVE',
  SET_SYNCHRONIZATION_SUMMARY = 'SET_SYNCHRONIZATION_SUMMARY',
  SET_CATEGORY_MATCHING_SUMMARY = 'SET_CATEGORY_MATCHING_SUMMARY',

  SET_REQUEST_STATE = 'SET_REQUEST_STATE',

  RESET = 'RESET',
}

export {MutationsTypes as default};
