services:
    php:
        image: phpdockerio/php72-cli
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        environment:
            _PS_ROOT_DIR_: /var/www/html
    node:
        image: node:10.16
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        environment:
            PATH: /var/www/html/_dev/node_modules/.bin/:$PATH
