enum ActionsTypes {
  GET_MODULES_VERSIONS = 'GET_MODULES_VERSIONS',
  TRIGGER_REGISTER_HOOK = 'TRIGGER_REGISTER_HOOK',
  FIX_UNREGISTERED_HOOKS = 'FIX_UNREGISTERED_HOOKS',
}

export {ActionsTypes as default};
