enum GettersTypes {
  GET_HOOKS_STATUS = 'GET_HOOKS_STATUS',
  GET_BILLING_SUBSCRIPTION_ACTIVE = 'GET_BILLING_SUBSCRIPTION_ACTIVE',
  GET_BILLING_SUBSCRIPTION_EXPIRING = 'GET_BILLING_SUBSCRIPTION_EXPIRING',
}

export {GettersTypes as default};
