services:
  PrestaShop\Module\PrestashopFacebook\Adapter\ConfigurationAdapter:
    class: PrestaShop\Module\PrestashopFacebook\Adapter\ConfigurationAdapter
    public: true
    arguments:
      - '@=service("ps_facebook.shop").id'

  PrestaShop\Module\PrestashopFacebook\Adapter\ToolsAdapter:
    class: PrestaShop\Module\PrestashopFacebook\Adapter\ToolsAdapter
    public: true

  Prestashop\ModuleLibGuzzleAdapter\ClientFactory:
    class: Prestashop\ModuleLibGuzzleAdapter\ClientFactory
    public: true
