services:
  PrestaShopCorp\Billing\Wrappers\BillingContextWrapper:
    class: 'PrestaShopCorp\Billing\Wrappers\BillingContextWrapper'
    arguments:
    - '@PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts'
    - '@ps_facebook.context'
    - '@ps_facebook.billing_env'

  PrestaShopCorp\Billing\Presenter\BillingPresenter:
    class: 'PrestaShopCorp\Billing\Presenter\BillingPresenter'
    public: true
    arguments:
    - '@PrestaShopCorp\Billing\Wrappers\BillingContextWrapper'
    - '@ps_facebook'

  PrestaShopCorp\Billing\Services\BillingService:
    class: 'PrestaShopCorp\Billing\Services\BillingService'
    public: true
    arguments:
    - '@PrestaShopCorp\Billing\Wrappers\BillingContextWrapper'
    - '@ps_facebook'
