services:
  PrestaShop\Module\PrestashopFacebook\Factory\GoogleCategoryEssentialsApiClientFactory:
    class: PrestaShop\Module\PrestashopFacebook\Factory\GoogleCategoryEssentialsApiClientFactory

  PrestaShop\Module\PrestashopFacebook\Factory\FacebookEssentialsApiClientFactory:
    class: PrestaShop\Module\PrestashopFacebook\Factory\FacebookEssentialsApiClientFactory

  PrestaShop\Module\PrestashopFacebook\Factory\PsApiClientFactory:
    class: PrestaShop\Module\PrestashopFacebook\Factory\PsApiClientFactory
    arguments:
     - '@PrestaShop\Module\PrestashopFacebook\Config\Env'
     - '@PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts'
     - '@PrestaShop\Module\PrestashopFacebook\API\EventSubscriber\AccountSuspendedSubscriber'
