services:
  PrestaShop\Module\PrestashopFacebook\Factory\FacebookEssentialsApiClientFactory:
    class: PrestaShop\Module\PrestashopFacebook\Factory\FacebookEssentialsApiClientFactory
    public: true
    arguments:
     - '@Prestashop\ModuleLibGuzzleAdapter\ClientFactory'

  PrestaShop\Module\PrestashopFacebook\Factory\PsApiClientFactory:
    class: PrestaShop\Module\PrestashopFacebook\Factory\PsApiClientFactory
    public: true
    arguments:
     - '@PrestaShop\Module\PrestashopFacebook\Config\Env'
     - '@PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts'
     - '@Prestashop\ModuleLibGuzzleAdapter\ClientFactory'
