services:
  PrestaShop\Module\PrestashopFacebook\Provider\AccessTokenProvider:
    class: PrestaShop\Module\PrestashopFacebook\Provider\AccessTokenProvider
    arguments:
      - '@PrestaShop\Module\PrestashopFacebook\Adapter\ConfigurationAdapter'
      - '@PrestaShop\Module\PrestashopFacebook\Handler\ErrorHandler\ErrorHandler'
      - '@ps_facebook.controller'
      - '@PrestaShop\Module\PrestashopFacebook\Factory\PsApiClientFactory'

  PrestaShop\Module\PrestashopFacebook\Provider\GoogleCategoryProviderInterface: '@PrestaShop\Module\PrestashopFacebook\Provider\GoogleCategoryProvider'

  PrestaShop\Module\PrestashopFacebook\Provider\GoogleCategoryProvider:
    class: PrestaShop\Module\PrestashopFacebook\Provider\GoogleCategoryProvider
    arguments:
      - '@PrestaShop\Module\PrestashopFacebook\Repository\GoogleCategoryRepository'

  PrestaShop\Module\PrestashopFacebook\Provider\FacebookDataProvider:
    class: PrestaShop\Module\PrestashopFacebook\Provider\FacebookDataProvider
    arguments:
      - '@PrestaShop\Module\PrestashopFacebook\API\FacebookClient'
      - '@PrestaShop\Module\PrestashopFacebook\Adapter\ConfigurationAdapter'

  PrestaShop\Module\PrestashopFacebook\Provider\FbeDataProvider:
    class: PrestaShop\Module\PrestashopFacebook\Provider\FbeDataProvider
    arguments:
      - '@PrestaShop\Module\PrestashopFacebook\Adapter\ConfigurationAdapter'

  PrestaShop\Module\PrestashopFacebook\Provider\FbeFeatureDataProvider:
    class: PrestaShop\Module\PrestashopFacebook\Provider\FbeFeatureDataProvider
    arguments:
      - '@PrestaShop\Module\PrestashopFacebook\API\FacebookClient'
      - '@PrestaShop\Module\PrestashopFacebook\Adapter\ConfigurationAdapter'

  PrestaShop\Module\PrestashopFacebook\Provider\EventDataProvider:
    class: PrestaShop\Module\PrestashopFacebook\Provider\EventDataProvider
    arguments:
      - '@PrestaShop\Module\PrestashopFacebook\Adapter\ToolsAdapter'
      - '@PrestaShop\Module\PrestashopFacebook\Adapter\ConfigurationAdapter'
      - '@PrestaShop\Module\PrestashopFacebook\Repository\ProductRepository'
      - '@ps_facebook.context'
      - '@ps_facebook'
      - '@PrestaShop\Module\PrestashopFacebook\Provider\ProductAvailabilityProviderInterface'
      - '@PrestaShop\Module\PrestashopFacebook\Repository\GoogleCategoryRepository'
      - '@PrestaShop\Module\PrestashopFacebook\Provider\GoogleCategoryProvider'

  PrestaShop\Module\PrestashopFacebook\Provider\ProductAvailabilityProviderInterface: '@PrestaShop\Module\PrestashopFacebook\Provider\ProductAvailabilityProvider'

  PrestaShop\Module\PrestashopFacebook\Provider\ProductAvailabilityProvider:
    class: PrestaShop\Module\PrestashopFacebook\Provider\ProductAvailabilityProvider

  PrestaShop\Module\PrestashopFacebook\Provider\MultishopDataProvider:
    class: PrestaShop\Module\PrestashopFacebook\Provider\MultishopDataProvider
    arguments:
      - '@PrestaShop\Module\PrestashopFacebook\Repository\ShopRepository'
      - '@PrestaShop\Module\Ps_facebook\Tracker\Segment'

  PrestaShop\Module\PrestashopFacebook\Provider\ProductSyncReportProvider:
    class: PrestaShop\Module\PrestashopFacebook\Provider\ProductSyncReportProvider
    arguments:
      - '@PrestaShop\Module\PrestashopFacebook\Adapter\ConfigurationAdapter'
      - '@PrestaShop\Module\PrestashopFacebook\Factory\PsApiClientFactory'
      - '@PrestaShop\Module\PrestashopFacebook\Handler\ErrorHandler\ErrorHandler'

  PrestaShop\Module\PrestashopFacebook\Provider\PrevalidationScanCacheProvider:
    class: PrestaShop\Module\PrestashopFacebook\Provider\PrevalidationScanCacheProvider
    arguments:
      - '@ps_facebook'
      - '@ps_facebook.cache'

  PrestaShop\Module\PrestashopFacebook\Provider\PrevalidationScanDataProvider:
    class: PrestaShop\Module\PrestashopFacebook\Provider\PrevalidationScanDataProvider
    arguments:
      - '@PrestaShop\Module\PrestashopFacebook\Provider\PrevalidationScanCacheProvider'
