name: Module Facebook CD Multishop

#on:
#  push:
#    branches:
#      - master
#  pull_request:
#    types: [opened,edited,reopened,synchronize,labeled]
on: [push]

env:
  MODULE_NAME: ps_facebook
  GCLOUD_TOKEN_PATH: ./token.json

jobs:

  build:
    name: Build ps_accounts and ps_checkout
    runs-on: ubuntu-latest
    timeout-minutes: 10
#    if: contains(github.event.pull_request.labels.*.name, 'quality assurance needed') || github.ref == 'refs/heads/master'

    steps:
      # Fixed babel build : https://github.com/ember-cli/ember-cli/issues/9235#issuecomment-635254959
      - name: Use Node.js 12.16.3
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.3

      - name: Checkout the repository
        uses: actions/checkout@v2

#      - name: Build ps checkout
#        working-directory: ps_checkout
#        run: |
#          yarn --cwd _dev/ add prestashop_accounts_vue_components
#          yarn --cwd _dev/ install
#          yarn --cwd _dev/ build
#          composer install
#          composer require prestashop/prestashop-accounts-auth:${ACCOUNTSAUTH_VERSION}
#        env:
#          VCOMPONENTS_VERSION: ${{ steps.version_vcomponents.outputs.VERSION }}
#          ACCOUNTSAUTH_VERSION: ${{ steps.version_auth.outputs.VERSION }}

#      - name: Delete old modules 1.7
#        continue-on-error: true
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SSH_HOST_INTEGRATION }}
#          username: ${{ secrets.SSH_USERNAME }}
#          key: ${{ secrets.SSH_KEY }}
#          script: |
#            sudo su -c 'rm -rf ${{ secrets.MULTISHOP_17_PATH }}/ps_accounts'
#            sudo su -c 'rm -rf ${{ secrets.MULTISHOP_17_PATH }}/ps_checkout'
#      - name: Delete old modules 1.6
#        continue-on-error: true
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SSH_HOST_INTEGRATION }}
#          username: ${{ secrets.SSH_USERNAME }}
#          key: ${{ secrets.SSH_KEY }}
#          script: |
#            sudo su -c 'rm -rf ${{ secrets.MULTISHOP_16_PATH }}/ps_accounts'
#            sudo su -c 'rm -rf ${{ secrets.MULTISHOP_16_PATH }}/ps_checkout'

      - name: Copy modules
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST_INTEGRATION }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: build