name: Module Facebook CI/CD

#on:
#  push:
#    branches:
#      - master
#  pull_request:
#    types: [opened,edited,reopened,synchronize,labeled]
on: [push]

env:
  MODULE_NAME: ps_facebook
  GCLOUD_TOKEN_PATH: ./token.json

jobs:

  build_stable:
    name: CI/CD integration ps_facebook
    runs-on: ubuntu-latest
    timeout-minutes: 10
    #    if: contains(github.event.pull_request.labels.*.name, 'quality assurance needed') || github.ref == 'refs/heads/master'

    steps:
      # Fixed babel build : https://github.com/ember-cli/ember-cli/issues/9235#issuecomment-635254959
      - name: Use Node.js 12.16.3
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.3

      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Build JS dependencies
        uses: PrestaShopCorp/github-action-build-js/12@v1.0
        with:
          cmd: npm
          path: ./_dev

      - name: Install composer dependencies
        run: composer install --no-dev -o

      - name: Clean-up project
        uses: PrestaShopCorp/github-action-clean-before-deploy@v1.0

      - name: Create & upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ github.event.repository.name }}
          path: ../

  push_stable:
    name: CI/CD integration ps_facebook
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: ${{ github.event.repository.name }}

      - run: ls -al

      - name: Copy modules
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST_PRODUCTION }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: ps_facebook

      - name: Move modules
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_PRODUCTION }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo su -c 'cp -R build/ps_facebook ${{ secrets.MODULE_PATH }}'
            sudo su -c 'chown -R www-data:www-data ${{ secrets.MODULE_PATH }}/ps_accounts'

      - name: Install modules
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_PRODUCTION }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo su -c 'docker exec $(docker ps -q -f "ancestor=prestashop/prestashop:1.7" -f "name=facebook") bin/console prestashop:module uninstall ps_facebook || true'
            sudo su -c 'docker exec $(docker ps -q -f "ancestor=prestashop/prestashop:1.7" -f "name=facebook") bin/console prestashop:module install ps_facebook'
