enum ActionsTypes {
  WARMUP_STORE = 'WARMUP_STORE',

  REQUEST_EXTERNAL_BUSINESS_ID = 'REQUEST_EXTERNAL_BUSINESS_ID',
  REQUEST_ONBOARDING_STATE = 'REQUEST_ONBOARDING_STATE',
}

export {ActionsTypes as default};
