enum GettersTypes {
  GET_EXTERNAL_BUSINESS_ID = 'GET_EXTERNAL_BUSINESS_ID',
  GET_ONBOARDING_STATE = 'GET_ONBOARDING_STATE',
  IS_USER_ONBOARDED = 'IS_USER_ONBOARDED',
}

export {GettersTypes as default};
