enum MutationsTypes {
  SET_EXTERNAL_BUSINESS_ID = 'SET_EXTERNAL_BUSINESS_ID',
  SET_ONBOARDED_CONTEXT = 'SET_ONBOARDED_CONTEXT',
  UPDATE_PIXEL_STATUS = 'UPDATE_PIXEL_STATUS',
}

export {MutationsTypes as default};
